// This file is auto-generated by scripts/upload-demo-images.ts
// DO NOT EDIT MANUALLY

export const demoImageMapping: Record<string, string> = {
  "/demo/demo-1.png": "demo-images/demo-1",
  "/demo/demo-2.png": "demo-images/demo-2",
  "/demo/demo-3.png": "demo-images/demo-3",
  "/demo/demo-4.png": "demo-images/demo-4",
  "/demo/demo-5.png": "demo-images/demo-5",
  "/demo/demo-6.png": "demo-images/demo-6",
  "/demo/demo-7.png": "demo-images/demo-7",
  "/demo/demo-8.png": "demo-images/demo-8",
  "/demo/demo-9.png": "demo-images/demo-9",
  "/demo/demo-10.png": "demo-images/demo-10",
  "/demo/demo-11.png": "demo-images/demo-11",
  "/demo/demo-12.png": "demo-images/demo-12",
  "/demo/demo-13.png": "demo-images/demo-13",
  "/demo/demo-14.png": "demo-images/demo-14",
  "/demo/demo-15.png": "demo-images/demo-15"
};

export const demoImagePublicIds: string[] = [
  "demo-images/demo-1",
  "demo-images/demo-2",
  "demo-images/demo-3",
  "demo-images/demo-4",
  "demo-images/demo-5",
  "demo-images/demo-6",
  "demo-images/demo-7",
  "demo-images/demo-8",
  "demo-images/demo-9",
  "demo-images/demo-10",
  "demo-images/demo-11",
  "demo-images/demo-12",
  "demo-images/demo-13",
  "demo-images/demo-14",
  "demo-images/demo-15",
];
